version: 2.1  
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0-node
    working_directory: ~/tmp
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Install sccache
          command: |
            sudo apt update
            sudo apt install snapd
            sudo snap install sccache --candidate
      - run:
          name: start-services
          command: |
            docker-compose -f docker-compose-runner.yml down
            docker-compose -f docker-compose-runner.yml up --build -d zk
            sccache --start-server
      - run:
          name: setup-env
          command: |
            echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
            echo $(pwd)/bin >> $GITHUB_PATH
      - run:
          name: lints
          command: |
            zk
            zk fmt --check
            zk lint --check

workflows:
    commit:
        jobs:
            - lint