version: 2.1
parameters:
    repo:
        type: string
        default: "rsksmart/rskj.git"
    version:
        type: string
        default: ""
    branch:
        type: string
        default: "master"
    slack_channel:
        type: string
        default: "integration-tests"
orbs:
  slack: circleci/slack@4.1
  
jobs:

  lint:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0-node

    working_directory: ~/tmp
    steps:
      - checkout
      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
      - name: start-services
        run: |
          docker-compose -f docker-compose-runner.yml down
          docker-compose -f docker-compose-runner.yml up --build -d zk
          ci_run sccache --start-server
      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
      - name: lints
        run: |
          ci_run zk
          ci_run zk fmt --check
          ci_run zk lint --check

workflows:
    commit:
        jobs:
            - lint