version: 2.1  
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0-node
    working_directory: ~/tmp
    steps:
      - checkout
      - run:
          name: setup-env
          command: |
            echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
            echo $(pwd)/bin >> $GITHUB_PATH
      - run:
          name: start-services
          command: |
            docker-compose -f docker-compose-runner.yml down
            docker-compose -f docker-compose-runner.yml up --build -d zk
            ci_run sccache --start-server
      - run:
          name: setup-env
          command: |
            echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
            echo $(pwd)/bin >> $GITHUB_PATH
      - run:
          name: lints
          command: |
            ci_run zk
            ci_run zk fmt --check
            ci_run zk lint --check

workflows:
    commit:
        jobs:
            - lint