name: ri-aggregation CI
on:
  push:
    branches:
    - rsk_merge_master_Dec2021
    #- rsk_port_initial
  
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: rsk_merge_master_Dec2021
        
      - name: start-services
        run: |
          docker-compose -f docker-compose-runner.yml down
          docker-compose -f docker-compose-runner.yml pull
          docker-compose -f docker-compose-runner.yml up --build -d rskj postgres zk 
          ci_run sccache --start-server &
          #docker-compose -f docker-compose-runner.yml ps -a
          #this won't work without port binding to host
          #curl http://localhost:4444 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
              
      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
      
      - name: init
        run: |
          ci_run ln -s /usr/src/keys/setup keys/setup
          ci_run zk
          ci_run zk run verify-keys unpack
          ci_run zk contract build
          ci_run zk db basic-setup
          ci_run zk run yarn

      - name: deploy contracts
        run: |
          ci_run zk run deploy-erc20 dev
          ci_run zk run deploy-eip1271

      - name: restart dev-liquidity-token-watcher and dev-ticker
        run: docker-compose -f docker-compose-runner.yml restart dev-liquidity-token-watcher dev-ticker

      - name: contracts-unit-tests
        run: ci_run zk test contracts

      - name: js-unit-tests
        run: ci_run zk test js

      - name: server-rust-unit-tests
        run: ci_run zk test server-rust
      
      - name: db-unit-tests
        run: ci_run zk test db
      
      - name: rust-api-unit-tests
        run: ci_run zk test rust-api


